### ISSUE TITLE
GitHub Action: Claude Code PR Generator from Issues

### ISSUE THREAD

**Issue by atxtechbro** [atxtechbro/dotfiles#228]
## Description

We need a GitHub Action that automates the process of converting GitHub issues into pull requests using Claude Code's CLI capabilities. This would significantly streamline our development workflow by reducing manual steps.

## Current Behavior

Currently, we need to manually read issues, create branches, write code, and submit PRs. This process could be automated using Claude Code's CLI capabilities.

## Expected Behavior

A GitHub Action that takes a GitHub issue as input and automatically generates a pull request using Claude Code. The action should:

1. Read the issue content and extract requirements
2. Use Claude Code CLI in non-interactive mode to generate code changes
3. Create a branch with the changes
4. Submit a pull request with the generated code
5. Use the dotfiles repository's AmazonQ.md file as CLAUDE.md for guidance

## Implementation Details

The GitHub Action should:

- Be triggered manually or on issue creation/labeling
- Use Claude Code's non-interactive mode (`claude -p`)
- Support custom system prompts via the AmazonQ.md file (renamed to CLAUDE.md)
- Leverage MCP configuration for enhanced capabilities
- Include proper error handling and logging
- Support configuration options for branch naming conventions and PR templates

## Example Workflow YAML

```yaml
name: Claude Code PR Generator
on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to process'
        required: true
  issues:
    types: [labeled]

jobs:
  generate-pr:
    if: ${{ github.event.label.name == 'ai-generate' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Claude Code
        run: npm install -g @anthropic-ai/claude-code
      
      - name: Process Issue
        id: process-issue
        run: |
          # Logic to extract issue content and generate code
          # using Claude Code CLI
      
      - name: Create Branch and PR
        run: |
          # Logic to create branch and PR with generated code
```

## References

- Claude Code CLI documentation: https://docs.anthropic.com/claude/docs/claude-code-sdk
- GitHub Actions workflow syntax
- Our dotfiles repository structure and philosophy
- Follows "tracer bullet" development approach from our AmazonQ.md file
