### ISSUE TITLE
feat(mcp): Add sonirico/mcp-shell server with fine-grained security controls

### ISSUE THREAD

**Issue by atxtechbro** [atxtechbro/dotfiles#302]
## Description
Add support for the [sonirico/mcp-shell](https://github.com/sonirico/mcp-shell) MCP server to enhance our Amazon Q CLI environment with fine-grained security controls for shell commands.

## Motivation
The sonirico/mcp-shell server provides important security features that align with our dotfiles philosophy:
- Whitelist/blacklist specific commands
- Block dangerous patterns (like `rm -rf` or `sudo`)
- Set execution time limits
- Restrict working directories
- Limit output size
- Enable audit logging

### 1. Installation Script
Create a script in `utils/install-mcp-shell.sh` that:
- Clones the repository or downloads the latest release
- Builds the server from source (Go required)
- Sets up the configuration file with secure defaults

### 2. Security Configuration
Create a default YAML configuration with these security settings:
```yaml
security:
  enabled: true
  allowed_commands:
    - ls
    - cat
    - grep
    - find
    - echo
  blocked_commands:
    - rm -rf
    - sudo
    - chmod
  blocked_patterns:
    - 'rm\s+.*-rf.*'
    - 'sudo\s+.*'
  max_execution_time: 30s
  working_directory: /tmp/mcp-workspace
  max_output_size: 1048576
  audit_log: true
```

### 3. Integration with Amazon Q
Add documentation and setup for integrating with Amazon Q CLI:
- Instructions for registering the MCP server with Amazon Q
- Example commands showing how to use the secure shell execution
- Explanation of security benefits

### 4. Documentation
- Add section to README.md explaining the security benefits
- Document how to customize the allowed/blocked commands
- Provide examples of common use cases

## Benefits
- Enhanced security when using shell commands with Amazon Q
- Protection against accidental or malicious destructive commands
- Audit trail for shell command execution
- Consistent with our "security first" approach

## References
- [sonirico/mcp-shell GitHub Repository](https://github.com/sonirico/mcp-shell)
- [Security Configuration Documentation](https://github.com/sonirico/mcp-shell?tab=readme-ov-file#security-configuration-yaml-only)
