### ISSUE TITLE
Subtraction PR Review: Remove unnecessary files from git-mcp-server

### ISSUE THREAD

**Issue by atxtechbro** [atxtechbro/dotfiles#455]
# Subtraction Creates Value: git-mcp-server Cleanup

Following a "subtraction creates value" mindset, this issue tracks removing unnecessary complexity from the git-mcp-server integration.

### 1. Remove Dockerfile
- **Why**: No containerization needed for dotfiles integration
- **Impact**: Removes Docker complexity, references to non-existent `uv.lock`
- **Action**: `rm Dockerfile`

### 2. Remove .venv from git tracking
- **Why**: 100+ MB of platform-specific dependencies that can be recreated
- **Impact**: Massive repo size reduction, proper Python hygiene
- **Action**: Add `.venv/` to `.gitignore` and `git rm -r --cached .venv`

### 3. Remove symlink complexity
- **Why**: `git_mcp_server.py` symlink adds unnecessary indirection
- **Impact**: Eliminates confusion, relies on proper entry points
- **Action**: `rm git_mcp_server.py`

### 4. Remove redundant __main__.py
- **Why**: 3-line file that just imports and calls main()
- **Impact**: Removes duplicate entry point methods
- **Action**: `rm src/mcp_server_git/__main__.py`

### 5. Remove tests directory (for now)
- **Why**: Empty test file slows iteration in experimental phase
- **Impact**: Faster development cycle, can add back if experiment succeeds
- **Action**: `rm -rf tests/`

### pyproject.toml
**Current**: Over-engineered with unnecessary metadata for personal use
**Proposed**: Strip to bare essentials:

```toml
[project]
name = "atxtechbro-git-mcp-server"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.7",
    "gitpython>=3.1.43", 
    "mcp>=1.0.0",
    "pydantic>=2.0.0",
]

[project.scripts]
atxtechbro-git-mcp-server = "mcp_server_git:main"
```

## ✅ Files to KEEP
- `server.py` - Core functionality
- `logging_utils.py` - Custom logging implementation  
- `__init__.py` - Required Python package structure
- `README.md` - Documentation
- `LICENSE` - Legal requirement

## Expected Impact
- **Size reduction**: ~100MB+ removed from repo
- **Complexity reduction**: Fewer ways to run the same thing
- **Clarity**: Only essential files remain
- **Speed**: Faster iteration without unnecessary overhead

## Principle
Every file must justify its existence for the specific use case of experimental MCP server integration in dotfiles, not follow generic Python project templates.

---
**Priority**: High - This cleanup supports the experimental nature and faster iteration goals.
